# -*- coding: utf-8 -*-
"""workforce_retention_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9TN-T1WJtNx52L7nlhjbxaVaOAbGoXY

# **Workforce Retention Intelligence System**

###This project predicts whether an employee is likely to leave the company using XGBoost, built on IBM's HR Analytics dataset.

###It includes feature engineering to capture risk factors like overtime, job hopping tendency, and travel stress, along with class imbalance handling and threshold tuning to make the model business-relevant rather.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

"""###Data Preprocessing & Feature Engineering"""

df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
print("Dataset loaded successfully")
df.head()

print("Shape:", df.shape)
print("\nInfo:")
print(df.info())

print("Missing values:", df.isnull().sum().sum(), "total missing values")
print("Duplicate rows:", df.duplicated().sum())

print("\nClass Distribution (Attrition):")
print(df['Attrition'].value_counts())
print(df['Attrition'].value_counts(normalize=True) * 100)

# Attrition Class Distribution Plot
plt.figure(figsize=(6,5))
sns.countplot(x='Attrition', data=df, palette='Set2')
plt.title('Attrition Class Distribution')
plt.xlabel('Attrition')
plt.ylabel('Count')
plt.show()

print(df['Over18'].unique())
print(df['StandardHours'].unique())

# These columns carry no predictive value (constant or ID columns)
drop_cols = ['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours']
df = df.drop(columns=drop_cols)

print("Shape after dropping columns:", df.shape)

# Encode target temporarily to check correlation
df['Attrition_encoded'] = df['Attrition'].map({'Yes': 1, 'No': 0})

plt.figure(figsize=(14,10))
sns.heatmap(df.corr(numeric_only=True), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Matrix - All Numeric Features vs Attrition')
plt.tight_layout()
plt.show()

target_corr = df.corr(numeric_only=True)['Attrition_encoded'].sort_values(key=abs, ascending=False)
print(target_corr)

# attrition rate by categorical feature
for col in ['BusinessTravel', 'Department', 'JobRole', 'OverTime']:
    print(f"\n{col}:")
    print(df.groupby(col)['Attrition_encoded'].mean().sort_values(ascending=False))

selected_features = [
    'Age', 'BusinessTravel', 'Department', 'DistanceFromHome',
    'EnvironmentSatisfaction', 'JobInvolvement', 'JobRole',
    'JobSatisfaction', 'MonthlyIncome', 'OverTime',
    'PerformanceRating', 'WorkLifeBalance', 'YearsAtCompany'
]

df = df[selected_features + ['Attrition']]
print(df.shape)
df.head()

# IncomePerYearAtCompany: income relative to tenure (avoids divide-by-zero for new joiners)
df['IncomePerYearAtCompany'] = df['MonthlyIncome'] / (df['YearsAtCompany'] + 1)

# HighOvertimeRisk: flag employees doing overtime as higher attrition risk
df['HighOvertimeRisk'] = df['OverTime'].apply(lambda x: 1 if x == 'Yes' else 0)

# TravelStress: frequent travel combined with long commute distance
df['TravelStress'] = df['BusinessTravel'].apply(
    lambda x: 2 if x == 'Travel_Frequently' else (1 if x == 'Travel_Rarely' else 0)
) * df['DistanceFromHome']

# JobHopperRisk: low satisfaction + low involvement = higher risk
df['JobHopperRisk'] = ((df['JobSatisfaction'] <= 2) & (df['JobInvolvement'] <= 2)).astype(int)

# LowIncomeHighDissatisfaction: underpaid employees who are also dissatisfied at same, are highest risk
df['LowIncomeHighDissatisfaction'] = ((df['MonthlyIncome'] < df['MonthlyIncome'].median()) &
                                       (df['JobSatisfaction'] <= 2)).astype(int)

df.head()

target_encoder = LabelEncoder()
df['Attrition'] = target_encoder.fit_transform(df['Attrition'])   # Yes=1, No=0

print(df['Attrition'].value_counts())

fig, axes = plt.subplots(1, 2, figsize=(14,5))

sns.barplot(x='OverTime', y='Attrition', data=df, hue='OverTime', ax=axes[0], palette='coolwarm', legend=False)
axes[0].set_title('Attrition Rate by OverTime')
axes[0].set_ylabel('Attrition Rate')

sns.barplot(x='BusinessTravel', y='Attrition', data=df, hue='BusinessTravel', ax=axes[1], palette='coolwarm', legend=False)
axes[1].set_title('Attrition Rate by Business Travel')
axes[1].set_ylabel('Attrition Rate')

plt.tight_layout()
plt.show()

categorical_cols = ['BusinessTravel', 'Department', 'JobRole', 'OverTime']
encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

encoders['Attrition'] = target_encoder

df.head()

X = df.drop('Attrition', axis=1)
y = df['Attrition']

print("Features:", X.columns.tolist())
print("X shape:", X.shape, " y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Train class distribution:\n", y_train.value_counts(normalize=True))

with open('encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

print("Encoders saved as encoders.pkl")

"""###Model Training & Evaluation"""

from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix
)
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate class imbalance ratio
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print("Scale pos weight:", scale_pos_weight)

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    eval_metric='logloss',
    scale_pos_weight=scale_pos_weight,   # handles class imbalance
    random_state=42
)

xgb_model.fit(X_train, y_train)
print("Model training complete")

y_pred = xgb_model.predict(X_test)
y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]   # probability of class 1(Attrition=Yes)

#tuning
from sklearn.metrics import classification_report

for threshold in [0.5, 0.4, 0.35, 0.3, 0.25, 0.2]:
    y_pred_adjusted = (y_pred_proba >= threshold).astype(int)
    prec = precision_score(y_test, y_pred_adjusted)
    rec = recall_score(y_test, y_pred_adjusted)
    f1 = f1_score(y_test, y_pred_adjusted)
    print(f"Threshold={threshold} -> Precision: {prec:.3f} | Recall: {rec:.3f} | F1: {f1:.3f}")

"""Class imbalance issue: default threshold (0.5) gave high accuracy (85%)

but very low recall (27%) - model was missing most employees who actually left.

Tested multiple thresholds (0.5 to 0.2) and found 0.3 gives the best balance between accuracy and recall.
"""

final_threshold = 0.3   # update

y_pred_final = (y_pred_proba >= final_threshold).astype(int)

print(f"Accuracy  : {accuracy_score(y_test, y_pred_final):.4f}")
print(f"Precision : {precision_score(y_test, y_pred_final):.4f}")
print(f"Recall    : {recall_score(y_test, y_pred_final):.4f}")
print(f"F1 Score  : {f1_score(y_test, y_pred_final):.4f}")
print(f"ROC-AUC   : {roc_auc_score(y_test, y_pred_proba):.4f}")

# Confusion Matrix using our chosen threshold (0.3)
cm = confusion_matrix(y_test, y_pred_final)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Attrition', 'Attrition'],
            yticklabels=['No Attrition', 'Attrition'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - XGBoost')
plt.show()

from sklearn.metrics import roc_curve

roc_auc = roc_auc_score(y_test, y_pred_proba)

fpr, tpr, _ = roc_curve(y_test, y_pred_proba)

plt.figure(figsize=(7,6))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC Curve (AUC = {roc_auc:.2f})')
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - XGBoost')
plt.legend()
plt.show()

importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': xgb_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(9,7))
sns.barplot(x='Importance', y='Feature', data=importance, color='teal')
plt.title('Feature Importance')
plt.tight_layout()
plt.show()

print(importance)

# top 10 highest-risk employees from test set

risk_df = X_test.copy()
risk_df['Actual'] = y_test.values
risk_df['Leave_Probability'] = y_pred_proba

top_risk = risk_df.sort_values(by='Leave_Probability', ascending=False).head(10)
print("Top 10 Employees at Highest Risk of Leaving:")
top_risk[['Age', 'MonthlyIncome', 'YearsAtCompany', 'OverTime', 'Leave_Probability']]

risk_levels = pd.cut(y_pred_proba, bins=[0, 0.3, 0.6, 1.0], labels=['Low Risk', 'Medium Risk', 'High Risk'])
risk_counts = risk_levels.value_counts()

plt.figure(figsize=(7,7))
colors = ['#34d399', '#fbbf24', '#f87171']
plt.pie(risk_counts, labels=risk_counts.index, autopct='%1.1f%%', colors=colors,
        wedgeprops=dict(width=0.4), startangle=90)
plt.title('Employee Risk Distribution', fontsize=14)
plt.show()

with open('xgb_attrition_model.pkl', 'wb') as f:
    pickle.dump(xgb_model, f)

print("Model saved as xgb_attrition_model.pkl")